--- drivers/net/wireless/realtek/Makefile
+++ drivers/net/wireless/realtek/Makefile
@@ -5,5 +5,6 @@
 obj-$(CONFIG_RTL8180)		+= rtl818x/
 obj-$(CONFIG_RTL8187)		+= rtl818x/
 obj-$(CONFIG_RTLWIFI)		+= rtlwifi/
+obj-$(CONFIG_RTL8XXXU)		+= rtl8xxxu/
 obj-$(CONFIG_88XXAU)		+= rtl8812au/
 
